package com.theaty.xiaoyuan.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.theaty.xiaoyuan.model.utils.StringConverter;
import com.theaty.xiaoyuan.model.xiaoyuan.Member;
import java.util.List;

import com.theaty.xiaoyuan.model.xiaoyuan.Album;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALBUM".
*/
public class AlbumDao extends AbstractDao<Album, Long> {

    public static final String TABLENAME = "ALBUM";

    /**
     * Properties of entity Album.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AlbumId = new Property(0, Long.class, "albumId", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Enabled = new Property(2, int.class, "enabled", false, "ENABLED");
        public final static Property Photos = new Property(3, String.class, "photos", false, "PHOTOS");
        public final static Property MemberId = new Property(4, Long.class, "memberId", false, "MEMBER_ID");
    }

    private DaoSession daoSession;

    private final StringConverter photosConverter = new StringConverter();
    private Query<Album> member_AlbumsQuery;

    public AlbumDao(DaoConfig config) {
        super(config);
    }
    
    public AlbumDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALBUM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: albumId
                "\"NAME\" TEXT," + // 1: name
                "\"ENABLED\" INTEGER NOT NULL ," + // 2: enabled
                "\"PHOTOS\" TEXT," + // 3: photos
                "\"MEMBER_ID\" INTEGER);"); // 4: memberId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALBUM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Album entity) {
        stmt.clearBindings();
 
        Long albumId = entity.getAlbumId();
        if (albumId != null) {
            stmt.bindLong(1, albumId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getEnabled());
 
        List photos = entity.getPhotos();
        if (photos != null) {
            stmt.bindString(4, photosConverter.convertToDatabaseValue(photos));
        }
 
        Long memberId = entity.getMemberId();
        if (memberId != null) {
            stmt.bindLong(5, memberId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Album entity) {
        stmt.clearBindings();
 
        Long albumId = entity.getAlbumId();
        if (albumId != null) {
            stmt.bindLong(1, albumId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getEnabled());
 
        List photos = entity.getPhotos();
        if (photos != null) {
            stmt.bindString(4, photosConverter.convertToDatabaseValue(photos));
        }
 
        Long memberId = entity.getMemberId();
        if (memberId != null) {
            stmt.bindLong(5, memberId);
        }
    }

    @Override
    protected final void attachEntity(Album entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Album readEntity(Cursor cursor, int offset) {
        Album entity = new Album( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // albumId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // enabled
            cursor.isNull(offset + 3) ? null : photosConverter.convertToEntityProperty(cursor.getString(offset + 3)), // photos
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // memberId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Album entity, int offset) {
        entity.setAlbumId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEnabled(cursor.getInt(offset + 2));
        entity.setPhotos(cursor.isNull(offset + 3) ? null : photosConverter.convertToEntityProperty(cursor.getString(offset + 3)));
        entity.setMemberId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Album entity, long rowId) {
        entity.setAlbumId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Album entity) {
        if(entity != null) {
            return entity.getAlbumId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Album entity) {
        return entity.getAlbumId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "albums" to-many relationship of Member. */
    public List<Album> _queryMember_Albums(Long albumId) {
        synchronized (this) {
            if (member_AlbumsQuery == null) {
                QueryBuilder<Album> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AlbumId.eq(null));
                member_AlbumsQuery = queryBuilder.build();
            }
        }
        Query<Album> query = member_AlbumsQuery.forCurrentThread();
        query.setParameter(0, albumId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMemberDao().getAllColumns());
            builder.append(" FROM ALBUM T");
            builder.append(" LEFT JOIN MEMBER T0 ON T.\"MEMBER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Album loadCurrentDeep(Cursor cursor, boolean lock) {
        Album entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Member member = loadCurrentOther(daoSession.getMemberDao(), cursor, offset);
        entity.setMember(member);

        return entity;    
    }

    public Album loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Album> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Album> list = new ArrayList<Album>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Album> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Album> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
