package com.theaty.xiaoyuan.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.theaty.xiaoyuan.model.xiaoyuan.Album;
import com.theaty.xiaoyuan.model.xiaoyuan.Comments;
import com.theaty.xiaoyuan.model.xiaoyuan.Member;
import com.theaty.xiaoyuan.model.xiaoyuan.Message;
import com.theaty.xiaoyuan.model.xiaoyuan.Play;
import com.theaty.xiaoyuan.model.xiaoyuan.Sign;
import com.theaty.xiaoyuan.model.xiaoyuan.Type;

import com.theaty.xiaoyuan.dao.AlbumDao;
import com.theaty.xiaoyuan.dao.CommentsDao;
import com.theaty.xiaoyuan.dao.MemberDao;
import com.theaty.xiaoyuan.dao.MessageDao;
import com.theaty.xiaoyuan.dao.PlayDao;
import com.theaty.xiaoyuan.dao.SignDao;
import com.theaty.xiaoyuan.dao.TypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig albumDaoConfig;
    private final DaoConfig commentsDaoConfig;
    private final DaoConfig memberDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig playDaoConfig;
    private final DaoConfig signDaoConfig;
    private final DaoConfig typeDaoConfig;

    private final AlbumDao albumDao;
    private final CommentsDao commentsDao;
    private final MemberDao memberDao;
    private final MessageDao messageDao;
    private final PlayDao playDao;
    private final SignDao signDao;
    private final TypeDao typeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        albumDaoConfig = daoConfigMap.get(AlbumDao.class).clone();
        albumDaoConfig.initIdentityScope(type);

        commentsDaoConfig = daoConfigMap.get(CommentsDao.class).clone();
        commentsDaoConfig.initIdentityScope(type);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        playDaoConfig = daoConfigMap.get(PlayDao.class).clone();
        playDaoConfig.initIdentityScope(type);

        signDaoConfig = daoConfigMap.get(SignDao.class).clone();
        signDaoConfig.initIdentityScope(type);

        typeDaoConfig = daoConfigMap.get(TypeDao.class).clone();
        typeDaoConfig.initIdentityScope(type);

        albumDao = new AlbumDao(albumDaoConfig, this);
        commentsDao = new CommentsDao(commentsDaoConfig, this);
        memberDao = new MemberDao(memberDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        playDao = new PlayDao(playDaoConfig, this);
        signDao = new SignDao(signDaoConfig, this);
        typeDao = new TypeDao(typeDaoConfig, this);

        registerDao(Album.class, albumDao);
        registerDao(Comments.class, commentsDao);
        registerDao(Member.class, memberDao);
        registerDao(Message.class, messageDao);
        registerDao(Play.class, playDao);
        registerDao(Sign.class, signDao);
        registerDao(Type.class, typeDao);
    }
    
    public void clear() {
        albumDaoConfig.clearIdentityScope();
        commentsDaoConfig.clearIdentityScope();
        memberDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        playDaoConfig.clearIdentityScope();
        signDaoConfig.clearIdentityScope();
        typeDaoConfig.clearIdentityScope();
    }

    public AlbumDao getAlbumDao() {
        return albumDao;
    }

    public CommentsDao getCommentsDao() {
        return commentsDao;
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public PlayDao getPlayDao() {
        return playDao;
    }

    public SignDao getSignDao() {
        return signDao;
    }

    public TypeDao getTypeDao() {
        return typeDao;
    }

}
