package com.theaty.xiaoyuan.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.theaty.xiaoyuan.model.xiaoyuan.Member;

import com.theaty.xiaoyuan.model.xiaoyuan.Comments;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMMENTS".
*/
public class CommentsDao extends AbstractDao<Comments, Long> {

    public static final String TABLENAME = "COMMENTS";

    /**
     * Properties of entity Comments.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CommentsId = new Property(0, Long.class, "commentsId", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Enabled = new Property(3, int.class, "enabled", false, "ENABLED");
        public final static Property MemberId = new Property(4, Long.class, "memberId", false, "MEMBER_ID");
    }

    private DaoSession daoSession;

    private Query<Comments> play_CommentsQuery;

    public CommentsDao(DaoConfig config) {
        super(config);
    }
    
    public CommentsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMMENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: commentsId
                "\"TITLE\" TEXT," + // 1: title
                "\"CONTENT\" TEXT," + // 2: content
                "\"ENABLED\" INTEGER NOT NULL ," + // 3: enabled
                "\"MEMBER_ID\" INTEGER);"); // 4: memberId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMMENTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Comments entity) {
        stmt.clearBindings();
 
        Long commentsId = entity.getCommentsId();
        if (commentsId != null) {
            stmt.bindLong(1, commentsId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getEnabled());
 
        Long memberId = entity.getMemberId();
        if (memberId != null) {
            stmt.bindLong(5, memberId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Comments entity) {
        stmt.clearBindings();
 
        Long commentsId = entity.getCommentsId();
        if (commentsId != null) {
            stmt.bindLong(1, commentsId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
        stmt.bindLong(4, entity.getEnabled());
 
        Long memberId = entity.getMemberId();
        if (memberId != null) {
            stmt.bindLong(5, memberId);
        }
    }

    @Override
    protected final void attachEntity(Comments entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Comments readEntity(Cursor cursor, int offset) {
        Comments entity = new Comments( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // commentsId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.getInt(offset + 3), // enabled
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // memberId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Comments entity, int offset) {
        entity.setCommentsId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEnabled(cursor.getInt(offset + 3));
        entity.setMemberId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Comments entity, long rowId) {
        entity.setCommentsId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Comments entity) {
        if(entity != null) {
            return entity.getCommentsId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Comments entity) {
        return entity.getCommentsId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "comments" to-many relationship of Play. */
    public List<Comments> _queryPlay_Comments(Long commentsId) {
        synchronized (this) {
            if (play_CommentsQuery == null) {
                QueryBuilder<Comments> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CommentsId.eq(null));
                play_CommentsQuery = queryBuilder.build();
            }
        }
        Query<Comments> query = play_CommentsQuery.forCurrentThread();
        query.setParameter(0, commentsId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMemberDao().getAllColumns());
            builder.append(" FROM COMMENTS T");
            builder.append(" LEFT JOIN MEMBER T0 ON T.\"MEMBER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Comments loadCurrentDeep(Cursor cursor, boolean lock) {
        Comments entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Member member = loadCurrentOther(daoSession.getMemberDao(), cursor, offset);
        entity.setMember(member);

        return entity;    
    }

    public Comments loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Comments> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Comments> list = new ArrayList<Comments>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Comments> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Comments> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
