package com.theaty.xiaoyuan.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.theaty.xiaoyuan.model.xiaoyuan.GoodsModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GOODS_MODEL".
*/
public class GoodsModelDao extends AbstractDao<GoodsModel, Integer> {

    public static final String TABLENAME = "GOODS_MODEL";

    /**
     * Properties of entity GoodsModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Goods_id = new Property(0, int.class, "goods_id", true, "GOODS_ID");
        public final static Property Goods_commonid = new Property(1, int.class, "goods_commonid", false, "GOODS_COMMONID");
        public final static Property Goods_name = new Property(2, String.class, "goods_name", false, "GOODS_NAME");
        public final static Property Goods_jingle = new Property(3, String.class, "goods_jingle", false, "GOODS_JINGLE");
        public final static Property Store_id = new Property(4, int.class, "store_id", false, "STORE_ID");
        public final static Property Store_name = new Property(5, String.class, "store_name", false, "STORE_NAME");
        public final static Property Gc_id = new Property(6, int.class, "gc_id", false, "GC_ID");
        public final static Property Gc_id_1 = new Property(7, int.class, "gc_id_1", false, "GC_ID_1");
        public final static Property Gc_id_2 = new Property(8, int.class, "gc_id_2", false, "GC_ID_2");
        public final static Property Gc_id_3 = new Property(9, int.class, "gc_id_3", false, "GC_ID_3");
        public final static Property Brand_id = new Property(10, int.class, "brand_id", false, "BRAND_ID");
        public final static Property Goods_price = new Property(11, Double.class, "goods_price", false, "GOODS_PRICE");
        public final static Property Goods_promotion_price = new Property(12, Double.class, "goods_promotion_price", false, "GOODS_PROMOTION_PRICE");
        public final static Property Goods_promotion_type = new Property(13, int.class, "goods_promotion_type", false, "GOODS_PROMOTION_TYPE");
        public final static Property Goods_marketprice = new Property(14, Double.class, "goods_marketprice", false, "GOODS_MARKETPRICE");
        public final static Property Goods_serial = new Property(15, String.class, "goods_serial", false, "GOODS_SERIAL");
        public final static Property Goods_storage_alarm = new Property(16, int.class, "goods_storage_alarm", false, "GOODS_STORAGE_ALARM");
        public final static Property Goods_click = new Property(17, int.class, "goods_click", false, "GOODS_CLICK");
        public final static Property Goods_salenum = new Property(18, int.class, "goods_salenum", false, "GOODS_SALENUM");
        public final static Property Goods_collect = new Property(19, int.class, "goods_collect", false, "GOODS_COLLECT");
        public final static Property Goods_spec = new Property(20, String.class, "goods_spec", false, "GOODS_SPEC");
        public final static Property Goods_storage = new Property(21, int.class, "goods_storage", false, "GOODS_STORAGE");
        public final static Property Goods_image = new Property(22, String.class, "goods_image", false, "GOODS_IMAGE");
        public final static Property Goods_state = new Property(23, int.class, "goods_state", false, "GOODS_STATE");
        public final static Property Goods_verify = new Property(24, int.class, "goods_verify", false, "GOODS_VERIFY");
        public final static Property Goods_addtime = new Property(25, int.class, "goods_addtime", false, "GOODS_ADDTIME");
        public final static Property Goods_edittime = new Property(26, int.class, "goods_edittime", false, "GOODS_EDITTIME");
        public final static Property GoodsClass = new Property(27, String.class, "goodsClass", false, "GOODS_CLASS");
        public final static Property Areaid_1 = new Property(28, int.class, "areaid_1", false, "AREAID_1");
        public final static Property Areaid_2 = new Property(29, int.class, "areaid_2", false, "AREAID_2");
        public final static Property Color_id = new Property(30, int.class, "color_id", false, "COLOR_ID");
        public final static Property Transport_id = new Property(31, int.class, "transport_id", false, "TRANSPORT_ID");
        public final static Property Goods_freight = new Property(32, Double.class, "goods_freight", false, "GOODS_FREIGHT");
        public final static Property Goods_vat = new Property(33, int.class, "goods_vat", false, "GOODS_VAT");
        public final static Property Goods_commend = new Property(34, int.class, "goods_commend", false, "GOODS_COMMEND");
        public final static Property Goods_stcids = new Property(35, String.class, "goods_stcids", false, "GOODS_STCIDS");
        public final static Property Evaluation_good_star = new Property(36, int.class, "evaluation_good_star", false, "EVALUATION_GOOD_STAR");
        public final static Property Evaluation_count = new Property(37, int.class, "evaluation_count", false, "EVALUATION_COUNT");
        public final static Property Is_virtual = new Property(38, int.class, "is_virtual", false, "IS_VIRTUAL");
        public final static Property Virtual_indate = new Property(39, int.class, "virtual_indate", false, "VIRTUAL_INDATE");
        public final static Property Virtual_limit = new Property(40, int.class, "virtual_limit", false, "VIRTUAL_LIMIT");
        public final static Property Virtual_invalid_refund = new Property(41, int.class, "virtual_invalid_refund", false, "VIRTUAL_INVALID_REFUND");
        public final static Property Is_appoint = new Property(42, int.class, "is_appoint", false, "IS_APPOINT");
        public final static Property Is_presell = new Property(43, int.class, "is_presell", false, "IS_PRESELL");
        public final static Property Have_gift = new Property(44, int.class, "have_gift", false, "HAVE_GIFT");
        public final static Property Is_own_shop = new Property(45, int.class, "is_own_shop", false, "IS_OWN_SHOP");
        public final static Property Class_time = new Property(46, int.class, "class_time", false, "CLASS_TIME");
        public final static Property GoodTime = new Property(47, java.util.Date.class, "goodTime", false, "GOOD_TIME");
        public final static Property Class_end = new Property(48, int.class, "class_end", false, "CLASS_END");
        public final static Property Video_name = new Property(49, String.class, "video_name", false, "VIDEO_NAME");
        public final static Property Audio_name = new Property(50, String.class, "audio_name", false, "AUDIO_NAME");
        public final static Property Goods_href = new Property(51, String.class, "goods_href", false, "GOODS_HREF");
        public final static Property Goods_url = new Property(52, String.class, "goods_url", false, "GOODS_URL");
        public final static Property Is_fav = new Property(53, int.class, "is_fav", false, "IS_FAV");
    }


    public GoodsModelDao(DaoConfig config) {
        super(config);
    }
    
    public GoodsModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOODS_MODEL\" (" + //
                "\"GOODS_ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: goods_id
                "\"GOODS_COMMONID\" INTEGER NOT NULL ," + // 1: goods_commonid
                "\"GOODS_NAME\" TEXT," + // 2: goods_name
                "\"GOODS_JINGLE\" TEXT," + // 3: goods_jingle
                "\"STORE_ID\" INTEGER NOT NULL ," + // 4: store_id
                "\"STORE_NAME\" TEXT," + // 5: store_name
                "\"GC_ID\" INTEGER NOT NULL ," + // 6: gc_id
                "\"GC_ID_1\" INTEGER NOT NULL ," + // 7: gc_id_1
                "\"GC_ID_2\" INTEGER NOT NULL ," + // 8: gc_id_2
                "\"GC_ID_3\" INTEGER NOT NULL ," + // 9: gc_id_3
                "\"BRAND_ID\" INTEGER NOT NULL ," + // 10: brand_id
                "\"GOODS_PRICE\" REAL," + // 11: goods_price
                "\"GOODS_PROMOTION_PRICE\" REAL," + // 12: goods_promotion_price
                "\"GOODS_PROMOTION_TYPE\" INTEGER NOT NULL ," + // 13: goods_promotion_type
                "\"GOODS_MARKETPRICE\" REAL," + // 14: goods_marketprice
                "\"GOODS_SERIAL\" TEXT," + // 15: goods_serial
                "\"GOODS_STORAGE_ALARM\" INTEGER NOT NULL ," + // 16: goods_storage_alarm
                "\"GOODS_CLICK\" INTEGER NOT NULL ," + // 17: goods_click
                "\"GOODS_SALENUM\" INTEGER NOT NULL ," + // 18: goods_salenum
                "\"GOODS_COLLECT\" INTEGER NOT NULL ," + // 19: goods_collect
                "\"GOODS_SPEC\" TEXT," + // 20: goods_spec
                "\"GOODS_STORAGE\" INTEGER NOT NULL ," + // 21: goods_storage
                "\"GOODS_IMAGE\" TEXT," + // 22: goods_image
                "\"GOODS_STATE\" INTEGER NOT NULL ," + // 23: goods_state
                "\"GOODS_VERIFY\" INTEGER NOT NULL ," + // 24: goods_verify
                "\"GOODS_ADDTIME\" INTEGER NOT NULL ," + // 25: goods_addtime
                "\"GOODS_EDITTIME\" INTEGER NOT NULL ," + // 26: goods_edittime
                "\"GOODS_CLASS\" TEXT," + // 27: goodsClass
                "\"AREAID_1\" INTEGER NOT NULL ," + // 28: areaid_1
                "\"AREAID_2\" INTEGER NOT NULL ," + // 29: areaid_2
                "\"COLOR_ID\" INTEGER NOT NULL ," + // 30: color_id
                "\"TRANSPORT_ID\" INTEGER NOT NULL ," + // 31: transport_id
                "\"GOODS_FREIGHT\" REAL," + // 32: goods_freight
                "\"GOODS_VAT\" INTEGER NOT NULL ," + // 33: goods_vat
                "\"GOODS_COMMEND\" INTEGER NOT NULL ," + // 34: goods_commend
                "\"GOODS_STCIDS\" TEXT," + // 35: goods_stcids
                "\"EVALUATION_GOOD_STAR\" INTEGER NOT NULL ," + // 36: evaluation_good_star
                "\"EVALUATION_COUNT\" INTEGER NOT NULL ," + // 37: evaluation_count
                "\"IS_VIRTUAL\" INTEGER NOT NULL ," + // 38: is_virtual
                "\"VIRTUAL_INDATE\" INTEGER NOT NULL ," + // 39: virtual_indate
                "\"VIRTUAL_LIMIT\" INTEGER NOT NULL ," + // 40: virtual_limit
                "\"VIRTUAL_INVALID_REFUND\" INTEGER NOT NULL ," + // 41: virtual_invalid_refund
                "\"IS_APPOINT\" INTEGER NOT NULL ," + // 42: is_appoint
                "\"IS_PRESELL\" INTEGER NOT NULL ," + // 43: is_presell
                "\"HAVE_GIFT\" INTEGER NOT NULL ," + // 44: have_gift
                "\"IS_OWN_SHOP\" INTEGER NOT NULL ," + // 45: is_own_shop
                "\"CLASS_TIME\" INTEGER NOT NULL ," + // 46: class_time
                "\"GOOD_TIME\" INTEGER," + // 47: goodTime
                "\"CLASS_END\" INTEGER NOT NULL ," + // 48: class_end
                "\"VIDEO_NAME\" TEXT," + // 49: video_name
                "\"AUDIO_NAME\" TEXT," + // 50: audio_name
                "\"GOODS_HREF\" TEXT," + // 51: goods_href
                "\"GOODS_URL\" TEXT," + // 52: goods_url
                "\"IS_FAV\" INTEGER NOT NULL );"); // 53: is_fav
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOODS_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GoodsModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getGoods_id());
        stmt.bindLong(2, entity.getGoods_commonid());
 
        String goods_name = entity.getGoods_name();
        if (goods_name != null) {
            stmt.bindString(3, goods_name);
        }
 
        String goods_jingle = entity.getGoods_jingle();
        if (goods_jingle != null) {
            stmt.bindString(4, goods_jingle);
        }
        stmt.bindLong(5, entity.getStore_id());
 
        String store_name = entity.getStore_name();
        if (store_name != null) {
            stmt.bindString(6, store_name);
        }
        stmt.bindLong(7, entity.getGc_id());
        stmt.bindLong(8, entity.getGc_id_1());
        stmt.bindLong(9, entity.getGc_id_2());
        stmt.bindLong(10, entity.getGc_id_3());
        stmt.bindLong(11, entity.getBrand_id());
 
        Double goods_price = entity.getGoods_price();
        if (goods_price != null) {
            stmt.bindDouble(12, goods_price);
        }
 
        Double goods_promotion_price = entity.getGoods_promotion_price();
        if (goods_promotion_price != null) {
            stmt.bindDouble(13, goods_promotion_price);
        }
        stmt.bindLong(14, entity.getGoods_promotion_type());
 
        Double goods_marketprice = entity.getGoods_marketprice();
        if (goods_marketprice != null) {
            stmt.bindDouble(15, goods_marketprice);
        }
 
        String goods_serial = entity.getGoods_serial();
        if (goods_serial != null) {
            stmt.bindString(16, goods_serial);
        }
        stmt.bindLong(17, entity.getGoods_storage_alarm());
        stmt.bindLong(18, entity.getGoods_click());
        stmt.bindLong(19, entity.getGoods_salenum());
        stmt.bindLong(20, entity.getGoods_collect());
 
        String goods_spec = entity.getGoods_spec();
        if (goods_spec != null) {
            stmt.bindString(21, goods_spec);
        }
        stmt.bindLong(22, entity.getGoods_storage());
 
        String goods_image = entity.getGoods_image();
        if (goods_image != null) {
            stmt.bindString(23, goods_image);
        }
        stmt.bindLong(24, entity.getGoods_state());
        stmt.bindLong(25, entity.getGoods_verify());
        stmt.bindLong(26, entity.getGoods_addtime());
        stmt.bindLong(27, entity.getGoods_edittime());
 
        String goodsClass = entity.getGoodsClass();
        if (goodsClass != null) {
            stmt.bindString(28, goodsClass);
        }
        stmt.bindLong(29, entity.getAreaid_1());
        stmt.bindLong(30, entity.getAreaid_2());
        stmt.bindLong(31, entity.getColor_id());
        stmt.bindLong(32, entity.getTransport_id());
 
        Double goods_freight = entity.getGoods_freight();
        if (goods_freight != null) {
            stmt.bindDouble(33, goods_freight);
        }
        stmt.bindLong(34, entity.getGoods_vat());
        stmt.bindLong(35, entity.getGoods_commend());
 
        String goods_stcids = entity.getGoods_stcids();
        if (goods_stcids != null) {
            stmt.bindString(36, goods_stcids);
        }
        stmt.bindLong(37, entity.getEvaluation_good_star());
        stmt.bindLong(38, entity.getEvaluation_count());
        stmt.bindLong(39, entity.getIs_virtual());
        stmt.bindLong(40, entity.getVirtual_indate());
        stmt.bindLong(41, entity.getVirtual_limit());
        stmt.bindLong(42, entity.getVirtual_invalid_refund());
        stmt.bindLong(43, entity.getIs_appoint());
        stmt.bindLong(44, entity.getIs_presell());
        stmt.bindLong(45, entity.getHave_gift());
        stmt.bindLong(46, entity.getIs_own_shop());
        stmt.bindLong(47, entity.getClass_time());
 
        java.util.Date goodTime = entity.getGoodTime();
        if (goodTime != null) {
            stmt.bindLong(48, goodTime.getTime());
        }
        stmt.bindLong(49, entity.getClass_end());
 
        String video_name = entity.getVideo_name();
        if (video_name != null) {
            stmt.bindString(50, video_name);
        }
 
        String audio_name = entity.getAudio_name();
        if (audio_name != null) {
            stmt.bindString(51, audio_name);
        }
 
        String goods_href = entity.getGoods_href();
        if (goods_href != null) {
            stmt.bindString(52, goods_href);
        }
 
        String goods_url = entity.getGoods_url();
        if (goods_url != null) {
            stmt.bindString(53, goods_url);
        }
        stmt.bindLong(54, entity.getIs_fav());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GoodsModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getGoods_id());
        stmt.bindLong(2, entity.getGoods_commonid());
 
        String goods_name = entity.getGoods_name();
        if (goods_name != null) {
            stmt.bindString(3, goods_name);
        }
 
        String goods_jingle = entity.getGoods_jingle();
        if (goods_jingle != null) {
            stmt.bindString(4, goods_jingle);
        }
        stmt.bindLong(5, entity.getStore_id());
 
        String store_name = entity.getStore_name();
        if (store_name != null) {
            stmt.bindString(6, store_name);
        }
        stmt.bindLong(7, entity.getGc_id());
        stmt.bindLong(8, entity.getGc_id_1());
        stmt.bindLong(9, entity.getGc_id_2());
        stmt.bindLong(10, entity.getGc_id_3());
        stmt.bindLong(11, entity.getBrand_id());
 
        Double goods_price = entity.getGoods_price();
        if (goods_price != null) {
            stmt.bindDouble(12, goods_price);
        }
 
        Double goods_promotion_price = entity.getGoods_promotion_price();
        if (goods_promotion_price != null) {
            stmt.bindDouble(13, goods_promotion_price);
        }
        stmt.bindLong(14, entity.getGoods_promotion_type());
 
        Double goods_marketprice = entity.getGoods_marketprice();
        if (goods_marketprice != null) {
            stmt.bindDouble(15, goods_marketprice);
        }
 
        String goods_serial = entity.getGoods_serial();
        if (goods_serial != null) {
            stmt.bindString(16, goods_serial);
        }
        stmt.bindLong(17, entity.getGoods_storage_alarm());
        stmt.bindLong(18, entity.getGoods_click());
        stmt.bindLong(19, entity.getGoods_salenum());
        stmt.bindLong(20, entity.getGoods_collect());
 
        String goods_spec = entity.getGoods_spec();
        if (goods_spec != null) {
            stmt.bindString(21, goods_spec);
        }
        stmt.bindLong(22, entity.getGoods_storage());
 
        String goods_image = entity.getGoods_image();
        if (goods_image != null) {
            stmt.bindString(23, goods_image);
        }
        stmt.bindLong(24, entity.getGoods_state());
        stmt.bindLong(25, entity.getGoods_verify());
        stmt.bindLong(26, entity.getGoods_addtime());
        stmt.bindLong(27, entity.getGoods_edittime());
 
        String goodsClass = entity.getGoodsClass();
        if (goodsClass != null) {
            stmt.bindString(28, goodsClass);
        }
        stmt.bindLong(29, entity.getAreaid_1());
        stmt.bindLong(30, entity.getAreaid_2());
        stmt.bindLong(31, entity.getColor_id());
        stmt.bindLong(32, entity.getTransport_id());
 
        Double goods_freight = entity.getGoods_freight();
        if (goods_freight != null) {
            stmt.bindDouble(33, goods_freight);
        }
        stmt.bindLong(34, entity.getGoods_vat());
        stmt.bindLong(35, entity.getGoods_commend());
 
        String goods_stcids = entity.getGoods_stcids();
        if (goods_stcids != null) {
            stmt.bindString(36, goods_stcids);
        }
        stmt.bindLong(37, entity.getEvaluation_good_star());
        stmt.bindLong(38, entity.getEvaluation_count());
        stmt.bindLong(39, entity.getIs_virtual());
        stmt.bindLong(40, entity.getVirtual_indate());
        stmt.bindLong(41, entity.getVirtual_limit());
        stmt.bindLong(42, entity.getVirtual_invalid_refund());
        stmt.bindLong(43, entity.getIs_appoint());
        stmt.bindLong(44, entity.getIs_presell());
        stmt.bindLong(45, entity.getHave_gift());
        stmt.bindLong(46, entity.getIs_own_shop());
        stmt.bindLong(47, entity.getClass_time());
 
        java.util.Date goodTime = entity.getGoodTime();
        if (goodTime != null) {
            stmt.bindLong(48, goodTime.getTime());
        }
        stmt.bindLong(49, entity.getClass_end());
 
        String video_name = entity.getVideo_name();
        if (video_name != null) {
            stmt.bindString(50, video_name);
        }
 
        String audio_name = entity.getAudio_name();
        if (audio_name != null) {
            stmt.bindString(51, audio_name);
        }
 
        String goods_href = entity.getGoods_href();
        if (goods_href != null) {
            stmt.bindString(52, goods_href);
        }
 
        String goods_url = entity.getGoods_url();
        if (goods_url != null) {
            stmt.bindString(53, goods_url);
        }
        stmt.bindLong(54, entity.getIs_fav());
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public GoodsModel readEntity(Cursor cursor, int offset) {
        GoodsModel entity = new GoodsModel( //
            cursor.getInt(offset + 0), // goods_id
            cursor.getInt(offset + 1), // goods_commonid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // goods_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // goods_jingle
            cursor.getInt(offset + 4), // store_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // store_name
            cursor.getInt(offset + 6), // gc_id
            cursor.getInt(offset + 7), // gc_id_1
            cursor.getInt(offset + 8), // gc_id_2
            cursor.getInt(offset + 9), // gc_id_3
            cursor.getInt(offset + 10), // brand_id
            cursor.isNull(offset + 11) ? null : cursor.getDouble(offset + 11), // goods_price
            cursor.isNull(offset + 12) ? null : cursor.getDouble(offset + 12), // goods_promotion_price
            cursor.getInt(offset + 13), // goods_promotion_type
            cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14), // goods_marketprice
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // goods_serial
            cursor.getInt(offset + 16), // goods_storage_alarm
            cursor.getInt(offset + 17), // goods_click
            cursor.getInt(offset + 18), // goods_salenum
            cursor.getInt(offset + 19), // goods_collect
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // goods_spec
            cursor.getInt(offset + 21), // goods_storage
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // goods_image
            cursor.getInt(offset + 23), // goods_state
            cursor.getInt(offset + 24), // goods_verify
            cursor.getInt(offset + 25), // goods_addtime
            cursor.getInt(offset + 26), // goods_edittime
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // goodsClass
            cursor.getInt(offset + 28), // areaid_1
            cursor.getInt(offset + 29), // areaid_2
            cursor.getInt(offset + 30), // color_id
            cursor.getInt(offset + 31), // transport_id
            cursor.isNull(offset + 32) ? null : cursor.getDouble(offset + 32), // goods_freight
            cursor.getInt(offset + 33), // goods_vat
            cursor.getInt(offset + 34), // goods_commend
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // goods_stcids
            cursor.getInt(offset + 36), // evaluation_good_star
            cursor.getInt(offset + 37), // evaluation_count
            cursor.getInt(offset + 38), // is_virtual
            cursor.getInt(offset + 39), // virtual_indate
            cursor.getInt(offset + 40), // virtual_limit
            cursor.getInt(offset + 41), // virtual_invalid_refund
            cursor.getInt(offset + 42), // is_appoint
            cursor.getInt(offset + 43), // is_presell
            cursor.getInt(offset + 44), // have_gift
            cursor.getInt(offset + 45), // is_own_shop
            cursor.getInt(offset + 46), // class_time
            cursor.isNull(offset + 47) ? null : new java.util.Date(cursor.getLong(offset + 47)), // goodTime
            cursor.getInt(offset + 48), // class_end
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // video_name
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // audio_name
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // goods_href
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // goods_url
            cursor.getInt(offset + 53) // is_fav
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GoodsModel entity, int offset) {
        entity.setGoods_id(cursor.getInt(offset + 0));
        entity.setGoods_commonid(cursor.getInt(offset + 1));
        entity.setGoods_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGoods_jingle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStore_id(cursor.getInt(offset + 4));
        entity.setStore_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGc_id(cursor.getInt(offset + 6));
        entity.setGc_id_1(cursor.getInt(offset + 7));
        entity.setGc_id_2(cursor.getInt(offset + 8));
        entity.setGc_id_3(cursor.getInt(offset + 9));
        entity.setBrand_id(cursor.getInt(offset + 10));
        entity.setGoods_price(cursor.isNull(offset + 11) ? null : cursor.getDouble(offset + 11));
        entity.setGoods_promotion_price(cursor.isNull(offset + 12) ? null : cursor.getDouble(offset + 12));
        entity.setGoods_promotion_type(cursor.getInt(offset + 13));
        entity.setGoods_marketprice(cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14));
        entity.setGoods_serial(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setGoods_storage_alarm(cursor.getInt(offset + 16));
        entity.setGoods_click(cursor.getInt(offset + 17));
        entity.setGoods_salenum(cursor.getInt(offset + 18));
        entity.setGoods_collect(cursor.getInt(offset + 19));
        entity.setGoods_spec(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setGoods_storage(cursor.getInt(offset + 21));
        entity.setGoods_image(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setGoods_state(cursor.getInt(offset + 23));
        entity.setGoods_verify(cursor.getInt(offset + 24));
        entity.setGoods_addtime(cursor.getInt(offset + 25));
        entity.setGoods_edittime(cursor.getInt(offset + 26));
        entity.setGoodsClass(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setAreaid_1(cursor.getInt(offset + 28));
        entity.setAreaid_2(cursor.getInt(offset + 29));
        entity.setColor_id(cursor.getInt(offset + 30));
        entity.setTransport_id(cursor.getInt(offset + 31));
        entity.setGoods_freight(cursor.isNull(offset + 32) ? null : cursor.getDouble(offset + 32));
        entity.setGoods_vat(cursor.getInt(offset + 33));
        entity.setGoods_commend(cursor.getInt(offset + 34));
        entity.setGoods_stcids(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setEvaluation_good_star(cursor.getInt(offset + 36));
        entity.setEvaluation_count(cursor.getInt(offset + 37));
        entity.setIs_virtual(cursor.getInt(offset + 38));
        entity.setVirtual_indate(cursor.getInt(offset + 39));
        entity.setVirtual_limit(cursor.getInt(offset + 40));
        entity.setVirtual_invalid_refund(cursor.getInt(offset + 41));
        entity.setIs_appoint(cursor.getInt(offset + 42));
        entity.setIs_presell(cursor.getInt(offset + 43));
        entity.setHave_gift(cursor.getInt(offset + 44));
        entity.setIs_own_shop(cursor.getInt(offset + 45));
        entity.setClass_time(cursor.getInt(offset + 46));
        entity.setGoodTime(cursor.isNull(offset + 47) ? null : new java.util.Date(cursor.getLong(offset + 47)));
        entity.setClass_end(cursor.getInt(offset + 48));
        entity.setVideo_name(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setAudio_name(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setGoods_href(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setGoods_url(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setIs_fav(cursor.getInt(offset + 53));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(GoodsModel entity, long rowId) {
        return entity.getGoods_id();
    }
    
    @Override
    public Integer getKey(GoodsModel entity) {
        if(entity != null) {
            return entity.getGoods_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GoodsModel entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
